default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: prescription_calculator

test:
  <<: *default
  database: prescription_calculator_test

production:
  <<: *default
  database: prescription_calculator_production 

